### ISSUE TITLE
Can't download datasets

### ISSUE THREAD

**Issue by kimeuichan** [wittyicon29/AppleAI--Apple-Disease-Detection-Using-CNN#1]
Hi, I would like to study CNN through this project.

But I am not able to download the dataset, could you please share it again?

**Comment by wittyicon29** [comment]
The dataset used was acquired through internet images and then filtering out the best ones for the dataset, I don't have the dataset files currently, but you can use this dataset from kaggle Kashmiri Apple Plant Disease Dataset, it would be almost same instead of apple images there are images of leaves of apple trees,
here's the link for it - [Kashmiri Apple Plant Disease Dataset](https://www.kaggle.com/datasets/hsmcaju/d-kap)
